name: tiki_taka_scoreboard_wearos
description: WearOS application for Tiki-Taka system for real-time scoreboard.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  bloc: ^9.2.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.5.0
  device_info_plus: ^13.1.0
  equatable: ^2.0.8
  firebase_analytics: ^12.4.2
  firebase_core: ^4.10.0
  firebase_crashlytics: ^5.2.3
  firebase_messaging: ^16.3.0
  firebase_performance: ^0.11.4+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^21.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.3.0
  get_it: ^9.2.1
  hugeicons: ^1.1.7
  intl: ^0.20.2
  package_info_plus: ^10.1.0
  shared_preferences: ^2.5.5
  wear_os_scrollbar: ^0.1.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.15.0
  fake_cloud_firestore: ^4.1.1
  file: ^7.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4
  mocktail: ^1.0.5
  test_coverage_badge: ^0.3.2
  very_good_analysis: ^10.2.0

flutter_launcher_icons:
  android: "ic_logo"
  image_path_android: "assets/app-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app-logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app-logo.png
    - assets/fonts/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Medium.ttf
          weight: 500
        - asset: assets/fonts/Merriweather-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/Orbitron-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Source Code Pro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700

