name: tiki_taka_scoreboard_wearos
description: WearOS application for Tiki-Taka system for real-time scoreboard.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: ">=3.44.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^9.2.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.8.0
  device_info_plus: ^13.2.0
  equatable: ^2.1.0
  firebase_analytics: ^12.4.6
  firebase_core: ^4.13.0
  firebase_crashlytics: ^5.2.7
  firebase_messaging: ^16.5.0
  firebase_performance: ^0.11.4+2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.2
  flutter_local_notifications: ^22.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.3.0
  get_it: ^9.2.1
  hugeicons: ^1.1.7
  intl: ^0.20.2
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.5
  wear_os_scrollbar: ^0.2.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.15.1
  fake_cloud_firestore: ^4.2.0
  file: ^7.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4
  mocktail: ^1.0.5
  test_coverage_badge: ^0.3.2
  very_good_analysis: ^10.3.0

flutter_launcher_icons:
  android: "ic_logo"
  image_path_android: "assets/app-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app-logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app-logo.png
    - assets/fonts/

  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: assets/fonts/GoogleSansFlex-VariableFont.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-VariableFont.ttf
        - asset: assets/fonts/Merriweather-Italic-VariableFont.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont.ttf
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont.ttf
        - asset: assets/fonts/Nunito-Italic-VariableFont.ttf
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont.ttf
        - asset: assets/fonts/OpenSans-Italic-VariableFont.ttf
          style: italic
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont.ttf
          style: italic
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont.ttf
        - asset: assets/fonts/SourceCodePro-Italic-VariableFont.ttf
          style: italic
