// Mocks generated by Mockito 5.4.6 from annotations
// in tiki_taka_scoreboard_wearos/test/app/cubit/app_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:user_repository/src/user_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveEnabledLeague({
    required String? league,
    required bool? enabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveEnabledLeague, [], {
              #league: league,
              #enabled: enabled,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<String> getEnabledLeagues() =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledLeagues, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i3.Future<void> saveLanguage({String? language = 'es_ES'}) =>
      (super.noSuchMethod(
            Invocation.method(#saveLanguage, [], {#language: language}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveBaseColor({String? baseColor = 'INDIGO'}) =>
      (super.noSuchMethod(
            Invocation.method(#saveBaseColor, [], {#baseColor: baseColor}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
